version: '2'

services:

    web:
        build:
            context: .
            args:
                buildenv: local

        env_file: .env

        ports:
            - "8099:80"

        volumes:
            - ./:/app/code

    mysql:
        image: mysql:5.7.11
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testZer0
            MYSQL_USER: testZer0-usr
            MYSQL_PASSWORD: testZer0877
        ports:
            - "33077:3306"

    redis:
        image: redis:3.0
        ports:
            - "63791:6379"

